spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SmartCityDB
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true