spring:
  datasource:
<<<<<<< Updated upstream
    url: jdbc:mysql://localhost:3306/SmartCityDB
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
=======
    url: jdbc:mysql://localhost/bd-smartcity-grupo15
    username: root
    password: admin
>>>>>>> Stashed changes
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
<<<<<<< Updated upstream
    show-sql: true
=======
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
       
>>>>>>> Stashed changes
